name: galpywheels
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - numexpr
  - setuptools
  - conda-forge::gsl
  - conda-forge::compilers
  - conda-forge::llvm-openmp
  - conda-forge::astropy>=2
