ci:
    autofix_prs: true
    autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs
  - id: check-yaml
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-backticks
- repo: https://github.com/hadialqattan/pycln
  rev: v2.3.0
  hooks:
    - id: pycln
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.6"
  hooks:
    - id: codespell
      args: ["-L", "thisE,thise,mye,tE,te,hist,ro,sav,ccompiler,aas",
      "-x","doc/source/_static/try-galpy.js"]
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
    - id: black
