ci:
    autofix_prs: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs
  - id: check-yaml
- repo: https://github.com/asottile/pyupgrade
  rev: v2.38.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: rst-backticks
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.1
  hooks:
    - id: pycln
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.0
  hooks:
  - id: nbqa-pyupgrade
    args: [--py37-plus]
  - id: nbqa-isort
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.1"
  hooks:
    - id: codespell
      args: ["-L", "thisE,thise,mye,tE,te,hist,ro",
      "-x","doc/source/_static/try-galpy.js"]
