name: Build manylinux wheels

# Update on every push
on: [push]

jobs:
  build:
    name: Build manylinux wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build manylinux2014_x86_64 wheels
        uses: ./.github/workflows/actions/manylinux2014_x86_64/
      - uses: actions/upload-artifact@v2-preview
        with:
          name: galpy-wheels-manylinux
          path: wheelhouse/*manylinux*.whl
