name: Wheel builder and uploader

# Update on every push and PR to main, and upon release creation
on:
  push:
    branches:
      - main
      - cibw
    paths:
      - '**'
      - '!tests/**'
      - '!doc/**'
      - '!.github/**'
      - '.github/workflows/wheels.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
  release:
    types: [created]

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Following numpy's setup
        buildplat:
        - [ubuntu-latest, manylinux_x86_64]
        - [macos-latest, macosx_*]
        - [windows-2019, win_amd64]
        - [windows-2019, win32]
        python: ["cp37", "cp38", "cp39", "cp310", "cp311"]
    steps:
      - uses: actions/checkout@v3
    # Install the GSL on Windows
      - uses: mamba-org/provision-with-micromamba@v13
        name: Install GSL (Windows)
        if: matrix.buildplat[1] == 'win_amd64' || matrix.buildplat[1] == 'win32'
        with:
          environment-name: gsl
          environment-file: false
          channels: conda-forge,anaconda
          extra-specs: gsl
        env:
          CONDA_FORCE_32BIT: ${{ matrix.buildplat[1] == 'win32' }}
      - name: Set GSL environment variables (Windows)
        if: matrix.buildplat[1] == 'win_amd64' || matrix.buildplat[1] == 'win32'
        shell: bash -l {0}
        run: |
          echo "INCLUDE=$CONDA_PREFIX\\Library\\include" >> $GITHUB_ENV
          echo "LIB=$CONDA_PREFIX\\Library\\lib" >> $GITHUB_ENV
          echo "LIBPATH=$CONDA_PREFIX\\Library\\lib" >> $GITHUB_ENV
          echo "$CONDA_PREFIX\\Library\\bin" >> $GITHUB_PATH # necessary when we don't activate the environment
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          CIBW_BEFORE_BUILD_LINUX: yum -y install gsl-devel
          CIBW_BEFORE_BUILD_MACOS: |
            brew install gsl
            echo 'CFLAGS="-I/usr/local/opt/gsl/include"'' >> $GITHUB_ENV
            echo 'LDFLAGS="-L/usr/local/opt/gsl/lib"'' >> $GITHUB_ENV
          CIBW_ENVIRONMENT_MACOS: CC=gcc-10 CXX=g++-
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python }}-${{ startsWith(matrix.buildplat[1], 'macosx') && 'macosx' || matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
